// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: veilnet.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Anchor_StartAnchor_FullMethodName       = "/veilnet.Anchor/StartAnchor"
	Anchor_StartAnchorWithFD_FullMethodName = "/veilnet.Anchor/StartAnchorWithFD"
	Anchor_StopAnchor_FullMethodName        = "/veilnet.Anchor/StopAnchor"
	Anchor_AddTaint_FullMethodName          = "/veilnet.Anchor/AddTaint"
	Anchor_RemoveTaint_FullMethodName       = "/veilnet.Anchor/RemoveTaint"
	Anchor_GetInfo_FullMethodName           = "/veilnet.Anchor/GetInfo"
	Anchor_GetRealmInfo_FullMethodName      = "/veilnet.Anchor/GetRealmInfo"
	Anchor_GetVeilInfo_FullMethodName       = "/veilnet.Anchor/GetVeilInfo"
	Anchor_GetTracerConfig_FullMethodName   = "/veilnet.Anchor/GetTracerConfig"
)

// AnchorClient is the client API for Anchor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnchorClient interface {
	StartAnchor(ctx context.Context, in *StartAnchorRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	StartAnchorWithFD(ctx context.Context, in *StartAnchorWithFDRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	StopAnchor(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AddTaint(ctx context.Context, in *AddTaintRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RemoveTaint(ctx context.Context, in *RemoveTaintRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetInfoResponse, error)
	GetRealmInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetRealmInfoResponse, error)
	GetVeilInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetVeilInfoResponse, error)
	GetTracerConfig(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TracerConfig, error)
}

type anchorClient struct {
	cc grpc.ClientConnInterface
}

func NewAnchorClient(cc grpc.ClientConnInterface) AnchorClient {
	return &anchorClient{cc}
}

func (c *anchorClient) StartAnchor(ctx context.Context, in *StartAnchorRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Anchor_StartAnchor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anchorClient) StartAnchorWithFD(ctx context.Context, in *StartAnchorWithFDRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Anchor_StartAnchorWithFD_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anchorClient) StopAnchor(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Anchor_StopAnchor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anchorClient) AddTaint(ctx context.Context, in *AddTaintRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Anchor_AddTaint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anchorClient) RemoveTaint(ctx context.Context, in *RemoveTaintRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Anchor_RemoveTaint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anchorClient) GetInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInfoResponse)
	err := c.cc.Invoke(ctx, Anchor_GetInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anchorClient) GetRealmInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetRealmInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRealmInfoResponse)
	err := c.cc.Invoke(ctx, Anchor_GetRealmInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anchorClient) GetVeilInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetVeilInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVeilInfoResponse)
	err := c.cc.Invoke(ctx, Anchor_GetVeilInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anchorClient) GetTracerConfig(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TracerConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TracerConfig)
	err := c.cc.Invoke(ctx, Anchor_GetTracerConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnchorServer is the server API for Anchor service.
// All implementations must embed UnimplementedAnchorServer
// for forward compatibility.
type AnchorServer interface {
	StartAnchor(context.Context, *StartAnchorRequest) (*emptypb.Empty, error)
	StartAnchorWithFD(context.Context, *StartAnchorWithFDRequest) (*emptypb.Empty, error)
	StopAnchor(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	AddTaint(context.Context, *AddTaintRequest) (*emptypb.Empty, error)
	RemoveTaint(context.Context, *RemoveTaintRequest) (*emptypb.Empty, error)
	GetInfo(context.Context, *emptypb.Empty) (*GetInfoResponse, error)
	GetRealmInfo(context.Context, *emptypb.Empty) (*GetRealmInfoResponse, error)
	GetVeilInfo(context.Context, *emptypb.Empty) (*GetVeilInfoResponse, error)
	GetTracerConfig(context.Context, *emptypb.Empty) (*TracerConfig, error)
	mustEmbedUnimplementedAnchorServer()
}

// UnimplementedAnchorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnchorServer struct{}

func (UnimplementedAnchorServer) StartAnchor(context.Context, *StartAnchorRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartAnchor not implemented")
}
func (UnimplementedAnchorServer) StartAnchorWithFD(context.Context, *StartAnchorWithFDRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartAnchorWithFD not implemented")
}
func (UnimplementedAnchorServer) StopAnchor(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopAnchor not implemented")
}
func (UnimplementedAnchorServer) AddTaint(context.Context, *AddTaintRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTaint not implemented")
}
func (UnimplementedAnchorServer) RemoveTaint(context.Context, *RemoveTaintRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveTaint not implemented")
}
func (UnimplementedAnchorServer) GetInfo(context.Context, *emptypb.Empty) (*GetInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInfo not implemented")
}
func (UnimplementedAnchorServer) GetRealmInfo(context.Context, *emptypb.Empty) (*GetRealmInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRealmInfo not implemented")
}
func (UnimplementedAnchorServer) GetVeilInfo(context.Context, *emptypb.Empty) (*GetVeilInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVeilInfo not implemented")
}
func (UnimplementedAnchorServer) GetTracerConfig(context.Context, *emptypb.Empty) (*TracerConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTracerConfig not implemented")
}
func (UnimplementedAnchorServer) mustEmbedUnimplementedAnchorServer() {}
func (UnimplementedAnchorServer) testEmbeddedByValue()                {}

// UnsafeAnchorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnchorServer will
// result in compilation errors.
type UnsafeAnchorServer interface {
	mustEmbedUnimplementedAnchorServer()
}

func RegisterAnchorServer(s grpc.ServiceRegistrar, srv AnchorServer) {
	// If the following call pancis, it indicates UnimplementedAnchorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Anchor_ServiceDesc, srv)
}

func _Anchor_StartAnchor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartAnchorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnchorServer).StartAnchor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Anchor_StartAnchor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnchorServer).StartAnchor(ctx, req.(*StartAnchorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Anchor_StartAnchorWithFD_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartAnchorWithFDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnchorServer).StartAnchorWithFD(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Anchor_StartAnchorWithFD_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnchorServer).StartAnchorWithFD(ctx, req.(*StartAnchorWithFDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Anchor_StopAnchor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnchorServer).StopAnchor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Anchor_StopAnchor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnchorServer).StopAnchor(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Anchor_AddTaint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTaintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnchorServer).AddTaint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Anchor_AddTaint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnchorServer).AddTaint(ctx, req.(*AddTaintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Anchor_RemoveTaint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveTaintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnchorServer).RemoveTaint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Anchor_RemoveTaint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnchorServer).RemoveTaint(ctx, req.(*RemoveTaintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Anchor_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnchorServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Anchor_GetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnchorServer).GetInfo(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Anchor_GetRealmInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnchorServer).GetRealmInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Anchor_GetRealmInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnchorServer).GetRealmInfo(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Anchor_GetVeilInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnchorServer).GetVeilInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Anchor_GetVeilInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnchorServer).GetVeilInfo(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Anchor_GetTracerConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnchorServer).GetTracerConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Anchor_GetTracerConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnchorServer).GetTracerConfig(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Anchor_ServiceDesc is the grpc.ServiceDesc for Anchor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Anchor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "veilnet.Anchor",
	HandlerType: (*AnchorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartAnchor",
			Handler:    _Anchor_StartAnchor_Handler,
		},
		{
			MethodName: "StartAnchorWithFD",
			Handler:    _Anchor_StartAnchorWithFD_Handler,
		},
		{
			MethodName: "StopAnchor",
			Handler:    _Anchor_StopAnchor_Handler,
		},
		{
			MethodName: "AddTaint",
			Handler:    _Anchor_AddTaint_Handler,
		},
		{
			MethodName: "RemoveTaint",
			Handler:    _Anchor_RemoveTaint_Handler,
		},
		{
			MethodName: "GetInfo",
			Handler:    _Anchor_GetInfo_Handler,
		},
		{
			MethodName: "GetRealmInfo",
			Handler:    _Anchor_GetRealmInfo_Handler,
		},
		{
			MethodName: "GetVeilInfo",
			Handler:    _Anchor_GetVeilInfo_Handler,
		},
		{
			MethodName: "GetTracerConfig",
			Handler:    _Anchor_GetTracerConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "veilnet.proto",
}
