// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: veilnet.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Anchor_StartAnchor_FullMethodName              = "/veilnet.Anchor/StartAnchor"
	Anchor_StopAnchor_FullMethodName               = "/veilnet.Anchor/StopAnchor"
	Anchor_CreateTUN_FullMethodName                = "/veilnet.Anchor/CreateTUN"
	Anchor_DestroyTUN_FullMethodName               = "/veilnet.Anchor/DestroyTUN"
	Anchor_AttachWithTUN_FullMethodName            = "/veilnet.Anchor/AttachWithTUN"
	Anchor_AttachWithFileDescriptor_FullMethodName = "/veilnet.Anchor/AttachWithFileDescriptor"
	Anchor_GetID_FullMethodName                    = "/veilnet.Anchor/GetID"
	Anchor_GetCIDR_FullMethodName                  = "/veilnet.Anchor/GetCIDR"
	Anchor_AddTaint_FullMethodName                 = "/veilnet.Anchor/AddTaint"
	Anchor_RemoveTaint_FullMethodName              = "/veilnet.Anchor/RemoveTaint"
)

// AnchorClient is the client API for Anchor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnchorClient interface {
	StartAnchor(ctx context.Context, in *StartAnchorRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	StopAnchor(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CreateTUN(ctx context.Context, in *CreateTUNRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DestroyTUN(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AttachWithTUN(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AttachWithFileDescriptor(ctx context.Context, in *AttachWithFileDescriptorRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetID(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetIDResponse, error)
	GetCIDR(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetCIDRResponse, error)
	AddTaint(ctx context.Context, in *AddTaintRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RemoveTaint(ctx context.Context, in *RemoveTaintRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type anchorClient struct {
	cc grpc.ClientConnInterface
}

func NewAnchorClient(cc grpc.ClientConnInterface) AnchorClient {
	return &anchorClient{cc}
}

func (c *anchorClient) StartAnchor(ctx context.Context, in *StartAnchorRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Anchor_StartAnchor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anchorClient) StopAnchor(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Anchor_StopAnchor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anchorClient) CreateTUN(ctx context.Context, in *CreateTUNRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Anchor_CreateTUN_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anchorClient) DestroyTUN(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Anchor_DestroyTUN_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anchorClient) AttachWithTUN(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Anchor_AttachWithTUN_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anchorClient) AttachWithFileDescriptor(ctx context.Context, in *AttachWithFileDescriptorRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Anchor_AttachWithFileDescriptor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anchorClient) GetID(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIDResponse)
	err := c.cc.Invoke(ctx, Anchor_GetID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anchorClient) GetCIDR(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetCIDRResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCIDRResponse)
	err := c.cc.Invoke(ctx, Anchor_GetCIDR_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anchorClient) AddTaint(ctx context.Context, in *AddTaintRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Anchor_AddTaint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anchorClient) RemoveTaint(ctx context.Context, in *RemoveTaintRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Anchor_RemoveTaint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnchorServer is the server API for Anchor service.
// All implementations must embed UnimplementedAnchorServer
// for forward compatibility.
type AnchorServer interface {
	StartAnchor(context.Context, *StartAnchorRequest) (*emptypb.Empty, error)
	StopAnchor(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	CreateTUN(context.Context, *CreateTUNRequest) (*emptypb.Empty, error)
	DestroyTUN(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	AttachWithTUN(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	AttachWithFileDescriptor(context.Context, *AttachWithFileDescriptorRequest) (*emptypb.Empty, error)
	GetID(context.Context, *emptypb.Empty) (*GetIDResponse, error)
	GetCIDR(context.Context, *emptypb.Empty) (*GetCIDRResponse, error)
	AddTaint(context.Context, *AddTaintRequest) (*emptypb.Empty, error)
	RemoveTaint(context.Context, *RemoveTaintRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedAnchorServer()
}

// UnimplementedAnchorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnchorServer struct{}

func (UnimplementedAnchorServer) StartAnchor(context.Context, *StartAnchorRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartAnchor not implemented")
}
func (UnimplementedAnchorServer) StopAnchor(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopAnchor not implemented")
}
func (UnimplementedAnchorServer) CreateTUN(context.Context, *CreateTUNRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTUN not implemented")
}
func (UnimplementedAnchorServer) DestroyTUN(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DestroyTUN not implemented")
}
func (UnimplementedAnchorServer) AttachWithTUN(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AttachWithTUN not implemented")
}
func (UnimplementedAnchorServer) AttachWithFileDescriptor(context.Context, *AttachWithFileDescriptorRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AttachWithFileDescriptor not implemented")
}
func (UnimplementedAnchorServer) GetID(context.Context, *emptypb.Empty) (*GetIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetID not implemented")
}
func (UnimplementedAnchorServer) GetCIDR(context.Context, *emptypb.Empty) (*GetCIDRResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCIDR not implemented")
}
func (UnimplementedAnchorServer) AddTaint(context.Context, *AddTaintRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTaint not implemented")
}
func (UnimplementedAnchorServer) RemoveTaint(context.Context, *RemoveTaintRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveTaint not implemented")
}
func (UnimplementedAnchorServer) mustEmbedUnimplementedAnchorServer() {}
func (UnimplementedAnchorServer) testEmbeddedByValue()                {}

// UnsafeAnchorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnchorServer will
// result in compilation errors.
type UnsafeAnchorServer interface {
	mustEmbedUnimplementedAnchorServer()
}

func RegisterAnchorServer(s grpc.ServiceRegistrar, srv AnchorServer) {
	// If the following call pancis, it indicates UnimplementedAnchorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Anchor_ServiceDesc, srv)
}

func _Anchor_StartAnchor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartAnchorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnchorServer).StartAnchor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Anchor_StartAnchor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnchorServer).StartAnchor(ctx, req.(*StartAnchorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Anchor_StopAnchor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnchorServer).StopAnchor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Anchor_StopAnchor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnchorServer).StopAnchor(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Anchor_CreateTUN_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTUNRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnchorServer).CreateTUN(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Anchor_CreateTUN_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnchorServer).CreateTUN(ctx, req.(*CreateTUNRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Anchor_DestroyTUN_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnchorServer).DestroyTUN(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Anchor_DestroyTUN_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnchorServer).DestroyTUN(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Anchor_AttachWithTUN_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnchorServer).AttachWithTUN(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Anchor_AttachWithTUN_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnchorServer).AttachWithTUN(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Anchor_AttachWithFileDescriptor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachWithFileDescriptorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnchorServer).AttachWithFileDescriptor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Anchor_AttachWithFileDescriptor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnchorServer).AttachWithFileDescriptor(ctx, req.(*AttachWithFileDescriptorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Anchor_GetID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnchorServer).GetID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Anchor_GetID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnchorServer).GetID(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Anchor_GetCIDR_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnchorServer).GetCIDR(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Anchor_GetCIDR_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnchorServer).GetCIDR(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Anchor_AddTaint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTaintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnchorServer).AddTaint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Anchor_AddTaint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnchorServer).AddTaint(ctx, req.(*AddTaintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Anchor_RemoveTaint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveTaintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnchorServer).RemoveTaint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Anchor_RemoveTaint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnchorServer).RemoveTaint(ctx, req.(*RemoveTaintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Anchor_ServiceDesc is the grpc.ServiceDesc for Anchor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Anchor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "veilnet.Anchor",
	HandlerType: (*AnchorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartAnchor",
			Handler:    _Anchor_StartAnchor_Handler,
		},
		{
			MethodName: "StopAnchor",
			Handler:    _Anchor_StopAnchor_Handler,
		},
		{
			MethodName: "CreateTUN",
			Handler:    _Anchor_CreateTUN_Handler,
		},
		{
			MethodName: "DestroyTUN",
			Handler:    _Anchor_DestroyTUN_Handler,
		},
		{
			MethodName: "AttachWithTUN",
			Handler:    _Anchor_AttachWithTUN_Handler,
		},
		{
			MethodName: "AttachWithFileDescriptor",
			Handler:    _Anchor_AttachWithFileDescriptor_Handler,
		},
		{
			MethodName: "GetID",
			Handler:    _Anchor_GetID_Handler,
		},
		{
			MethodName: "GetCIDR",
			Handler:    _Anchor_GetCIDR_Handler,
		},
		{
			MethodName: "AddTaint",
			Handler:    _Anchor_AddTaint_Handler,
		},
		{
			MethodName: "RemoveTaint",
			Handler:    _Anchor_RemoveTaint_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "veilnet.proto",
}
