// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: veilnet.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_RTC_OFFER                 MessageType = 0
	MessageType_RTC_ANSWER                MessageType = 1
	MessageType_CANDIDATE_OFFER           MessageType = 2
	MessageType_ICE_CANDIDATE             MessageType = 3
	MessageType_ICE_OFFER                 MessageType = 4
	MessageType_ICE_ANSWER                MessageType = 5
	MessageType_DNS_QUERY                 MessageType = 6
	MessageType_DNS_ANSWER                MessageType = 7
	MessageType_ARP_REQUEST               MessageType = 8
	MessageType_ARP_RESPONSE              MessageType = 9
	MessageType_ARP_UPDATE                MessageType = 10
	MessageType_STREAM_DISCOVERY          MessageType = 11
	MessageType_STREAM_DISCOVERY_RESPONSE MessageType = 12
	MessageType_STREAM_REQUEST            MessageType = 13
	MessageType_STREAM_RESPONSE           MessageType = 14
	MessageType_STREAM_UPDATE             MessageType = 15
	MessageType_ECHO                      MessageType = 16
	MessageType_DATA                      MessageType = 17
	MessageType_ADD_REMOTE_NETWORK        MessageType = 18
	MessageType_REMOVE_REMOTE_NETWORK     MessageType = 19
	MessageType_CMD                       MessageType = 20
	MessageType_CMD_RESPONSE              MessageType = 21
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:  "RTC_OFFER",
		1:  "RTC_ANSWER",
		2:  "CANDIDATE_OFFER",
		3:  "ICE_CANDIDATE",
		4:  "ICE_OFFER",
		5:  "ICE_ANSWER",
		6:  "DNS_QUERY",
		7:  "DNS_ANSWER",
		8:  "ARP_REQUEST",
		9:  "ARP_RESPONSE",
		10: "ARP_UPDATE",
		11: "STREAM_DISCOVERY",
		12: "STREAM_DISCOVERY_RESPONSE",
		13: "STREAM_REQUEST",
		14: "STREAM_RESPONSE",
		15: "STREAM_UPDATE",
		16: "ECHO",
		17: "DATA",
		18: "ADD_REMOTE_NETWORK",
		19: "REMOVE_REMOTE_NETWORK",
		20: "CMD",
		21: "CMD_RESPONSE",
	}
	MessageType_value = map[string]int32{
		"RTC_OFFER":                 0,
		"RTC_ANSWER":                1,
		"CANDIDATE_OFFER":           2,
		"ICE_CANDIDATE":             3,
		"ICE_OFFER":                 4,
		"ICE_ANSWER":                5,
		"DNS_QUERY":                 6,
		"DNS_ANSWER":                7,
		"ARP_REQUEST":               8,
		"ARP_RESPONSE":              9,
		"ARP_UPDATE":                10,
		"STREAM_DISCOVERY":          11,
		"STREAM_DISCOVERY_RESPONSE": 12,
		"STREAM_REQUEST":            13,
		"STREAM_RESPONSE":           14,
		"STREAM_UPDATE":             15,
		"ECHO":                      16,
		"DATA":                      17,
		"ADD_REMOTE_NETWORK":        18,
		"REMOVE_REMOTE_NETWORK":     19,
		"CMD":                       20,
		"CMD_RESPONSE":              21,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_veilnet_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_veilnet_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_veilnet_proto_rawDescGZIP(), []int{0}
}

type CmdType int32

const (
	CmdType_SHUTDOWN             CmdType = 0
	CmdType_QUERY_LOCAL_NETWORK  CmdType = 1
	CmdType_QUERY_REMOTE_NETWORK CmdType = 2
	CmdType_SCOPE_UPDATE         CmdType = 3
)

// Enum value maps for CmdType.
var (
	CmdType_name = map[int32]string{
		0: "SHUTDOWN",
		1: "QUERY_LOCAL_NETWORK",
		2: "QUERY_REMOTE_NETWORK",
		3: "SCOPE_UPDATE",
	}
	CmdType_value = map[string]int32{
		"SHUTDOWN":             0,
		"QUERY_LOCAL_NETWORK":  1,
		"QUERY_REMOTE_NETWORK": 2,
		"SCOPE_UPDATE":         3,
	}
)

func (x CmdType) Enum() *CmdType {
	p := new(CmdType)
	*p = x
	return p
}

func (x CmdType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CmdType) Descriptor() protoreflect.EnumDescriptor {
	return file_veilnet_proto_enumTypes[1].Descriptor()
}

func (CmdType) Type() protoreflect.EnumType {
	return &file_veilnet_proto_enumTypes[1]
}

func (x CmdType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CmdType.Descriptor instead.
func (CmdType) EnumDescriptor() ([]byte, []int) {
	return file_veilnet_proto_rawDescGZIP(), []int{1}
}

type Role int32

const (
	Role_GUARDIAN Role = 0
	Role_CONFLUX  Role = 1
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "GUARDIAN",
		1: "CONFLUX",
	}
	Role_value = map[string]int32{
		"GUARDIAN": 0,
		"CONFLUX":  1,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_veilnet_proto_enumTypes[2].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_veilnet_proto_enumTypes[2]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_veilnet_proto_rawDescGZIP(), []int{2}
}

type Header struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Type           MessageType            `protobuf:"varint,1,opt,name=type,proto3,enum=veilnet.MessageType" json:"type,omitempty"`
	Signature      string                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Role           Role                   `protobuf:"varint,3,opt,name=role,proto3,enum=veilnet.Role" json:"role,omitempty"`
	Length         uint32                 `protobuf:"varint,4,opt,name=length,proto3" json:"length,omitempty"`
	MldsaPublicKey []byte                 `protobuf:"bytes,5,opt,name=mldsa_public_key,json=mldsaPublicKey,proto3" json:"mldsa_public_key,omitempty"`
	MldsaSignature []byte                 `protobuf:"bytes,6,opt,name=mldsa_signature,json=mldsaSignature,proto3" json:"mldsa_signature,omitempty"`
	Scopes         [][]byte               `protobuf:"bytes,7,rep,name=scopes,proto3" json:"scopes,omitempty"`
	Taints         [][]byte               `protobuf:"bytes,8,rep,name=taints,proto3" json:"taints,omitempty"`
	Timestamp      int64                  `protobuf:"varint,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_veilnet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_veilnet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_veilnet_proto_rawDescGZIP(), []int{0}
}

func (x *Header) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_RTC_OFFER
}

func (x *Header) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *Header) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_GUARDIAN
}

func (x *Header) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *Header) GetMldsaPublicKey() []byte {
	if x != nil {
		return x.MldsaPublicKey
	}
	return nil
}

func (x *Header) GetMldsaSignature() []byte {
	if x != nil {
		return x.MldsaSignature
	}
	return nil
}

func (x *Header) GetScopes() [][]byte {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *Header) GetTaints() [][]byte {
	if x != nil {
		return x.Taints
	}
	return nil
}

func (x *Header) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type RTC_Offer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TetherId      string                 `protobuf:"bytes,1,opt,name=tether_id,json=tetherId,proto3" json:"tether_id,omitempty"`
	Signature     string                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Offer         []byte                 `protobuf:"bytes,3,opt,name=offer,proto3" json:"offer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RTC_Offer) Reset() {
	*x = RTC_Offer{}
	mi := &file_veilnet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RTC_Offer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTC_Offer) ProtoMessage() {}

func (x *RTC_Offer) ProtoReflect() protoreflect.Message {
	mi := &file_veilnet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTC_Offer.ProtoReflect.Descriptor instead.
func (*RTC_Offer) Descriptor() ([]byte, []int) {
	return file_veilnet_proto_rawDescGZIP(), []int{1}
}

func (x *RTC_Offer) GetTetherId() string {
	if x != nil {
		return x.TetherId
	}
	return ""
}

func (x *RTC_Offer) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *RTC_Offer) GetOffer() []byte {
	if x != nil {
		return x.Offer
	}
	return nil
}

type RTC_Answer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TetherId      string                 `protobuf:"bytes,1,opt,name=tether_id,json=tetherId,proto3" json:"tether_id,omitempty"`
	Signature     string                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Answer        []byte                 `protobuf:"bytes,3,opt,name=answer,proto3" json:"answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RTC_Answer) Reset() {
	*x = RTC_Answer{}
	mi := &file_veilnet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RTC_Answer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTC_Answer) ProtoMessage() {}

func (x *RTC_Answer) ProtoReflect() protoreflect.Message {
	mi := &file_veilnet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTC_Answer.ProtoReflect.Descriptor instead.
func (*RTC_Answer) Descriptor() ([]byte, []int) {
	return file_veilnet_proto_rawDescGZIP(), []int{2}
}

func (x *RTC_Answer) GetTetherId() string {
	if x != nil {
		return x.TetherId
	}
	return ""
}

func (x *RTC_Answer) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *RTC_Answer) GetAnswer() []byte {
	if x != nil {
		return x.Answer
	}
	return nil
}

type CandidateOffer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TetherId      string                 `protobuf:"bytes,1,opt,name=tether_id,json=tetherId,proto3" json:"tether_id,omitempty"`
	Candidate     string                 `protobuf:"bytes,2,opt,name=candidate,proto3" json:"candidate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CandidateOffer) Reset() {
	*x = CandidateOffer{}
	mi := &file_veilnet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CandidateOffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandidateOffer) ProtoMessage() {}

func (x *CandidateOffer) ProtoReflect() protoreflect.Message {
	mi := &file_veilnet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandidateOffer.ProtoReflect.Descriptor instead.
func (*CandidateOffer) Descriptor() ([]byte, []int) {
	return file_veilnet_proto_rawDescGZIP(), []int{3}
}

func (x *CandidateOffer) GetTetherId() string {
	if x != nil {
		return x.TetherId
	}
	return ""
}

func (x *CandidateOffer) GetCandidate() string {
	if x != nil {
		return x.Candidate
	}
	return ""
}

type CandidateAccept struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CandidateAccept) Reset() {
	*x = CandidateAccept{}
	mi := &file_veilnet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CandidateAccept) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandidateAccept) ProtoMessage() {}

func (x *CandidateAccept) ProtoReflect() protoreflect.Message {
	mi := &file_veilnet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandidateAccept.ProtoReflect.Descriptor instead.
func (*CandidateAccept) Descriptor() ([]byte, []int) {
	return file_veilnet_proto_rawDescGZIP(), []int{4}
}

type ICE struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TetherId      string                 `protobuf:"bytes,1,opt,name=tether_id,json=tetherId,proto3" json:"tether_id,omitempty"`
	Signature     string                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Ufrag         string                 `protobuf:"bytes,3,opt,name=ufrag,proto3" json:"ufrag,omitempty"`
	Pwd           string                 `protobuf:"bytes,4,opt,name=pwd,proto3" json:"pwd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ICE) Reset() {
	*x = ICE{}
	mi := &file_veilnet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ICE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ICE) ProtoMessage() {}

func (x *ICE) ProtoReflect() protoreflect.Message {
	mi := &file_veilnet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ICE.ProtoReflect.Descriptor instead.
func (*ICE) Descriptor() ([]byte, []int) {
	return file_veilnet_proto_rawDescGZIP(), []int{5}
}

func (x *ICE) GetTetherId() string {
	if x != nil {
		return x.TetherId
	}
	return ""
}

func (x *ICE) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *ICE) GetUfrag() string {
	if x != nil {
		return x.Ufrag
	}
	return ""
}

func (x *ICE) GetPwd() string {
	if x != nil {
		return x.Pwd
	}
	return ""
}

type ArpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     string                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArpRequest) Reset() {
	*x = ArpRequest{}
	mi := &file_veilnet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArpRequest) ProtoMessage() {}

func (x *ArpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_veilnet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArpRequest.ProtoReflect.Descriptor instead.
func (*ArpRequest) Descriptor() ([]byte, []int) {
	return file_veilnet_proto_rawDescGZIP(), []int{6}
}

func (x *ArpRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type ArpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     string                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	Dst           string                 `protobuf:"bytes,2,opt,name=dst,proto3" json:"dst,omitempty"`
	Weight        int64                  `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	Hops          int64                  `protobuf:"varint,4,opt,name=hops,proto3" json:"hops,omitempty"`
	Path          []string               `protobuf:"bytes,5,rep,name=path,proto3" json:"path,omitempty"`
	Id            string                 `protobuf:"bytes,6,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArpResponse) Reset() {
	*x = ArpResponse{}
	mi := &file_veilnet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArpResponse) ProtoMessage() {}

func (x *ArpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_veilnet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArpResponse.ProtoReflect.Descriptor instead.
func (*ArpResponse) Descriptor() ([]byte, []int) {
	return file_veilnet_proto_rawDescGZIP(), []int{7}
}

func (x *ArpResponse) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *ArpResponse) GetDst() string {
	if x != nil {
		return x.Dst
	}
	return ""
}

func (x *ArpResponse) GetWeight() int64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *ArpResponse) GetHops() int64 {
	if x != nil {
		return x.Hops
	}
	return 0
}

func (x *ArpResponse) GetPath() []string {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *ArpResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ArpUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Hops          int64                  `protobuf:"varint,2,opt,name=hops,proto3" json:"hops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArpUpdate) Reset() {
	*x = ArpUpdate{}
	mi := &file_veilnet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArpUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArpUpdate) ProtoMessage() {}

func (x *ArpUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_veilnet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArpUpdate.ProtoReflect.Descriptor instead.
func (*ArpUpdate) Descriptor() ([]byte, []int) {
	return file_veilnet_proto_rawDescGZIP(), []int{8}
}

func (x *ArpUpdate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ArpUpdate) GetHops() int64 {
	if x != nil {
		return x.Hops
	}
	return 0
}

type DNSOffer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNSOffer) Reset() {
	*x = DNSOffer{}
	mi := &file_veilnet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSOffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSOffer) ProtoMessage() {}

func (x *DNSOffer) ProtoReflect() protoreflect.Message {
	mi := &file_veilnet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSOffer.ProtoReflect.Descriptor instead.
func (*DNSOffer) Descriptor() ([]byte, []int) {
	return file_veilnet_proto_rawDescGZIP(), []int{9}
}

func (x *DNSOffer) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type DNSQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNSQuery) Reset() {
	*x = DNSQuery{}
	mi := &file_veilnet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSQuery) ProtoMessage() {}

func (x *DNSQuery) ProtoReflect() protoreflect.Message {
	mi := &file_veilnet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSQuery.ProtoReflect.Descriptor instead.
func (*DNSQuery) Descriptor() ([]byte, []int) {
	return file_veilnet_proto_rawDescGZIP(), []int{10}
}

func (x *DNSQuery) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type DNSResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNSResponse) Reset() {
	*x = DNSResponse{}
	mi := &file_veilnet_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSResponse) ProtoMessage() {}

func (x *DNSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_veilnet_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSResponse.ProtoReflect.Descriptor instead.
func (*DNSResponse) Descriptor() ([]byte, []int) {
	return file_veilnet_proto_rawDescGZIP(), []int{11}
}

func (x *DNSResponse) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type StreamDiscovery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamDiscovery) Reset() {
	*x = StreamDiscovery{}
	mi := &file_veilnet_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamDiscovery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamDiscovery) ProtoMessage() {}

func (x *StreamDiscovery) ProtoReflect() protoreflect.Message {
	mi := &file_veilnet_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamDiscovery.ProtoReflect.Descriptor instead.
func (*StreamDiscovery) Descriptor() ([]byte, []int) {
	return file_veilnet_proto_rawDescGZIP(), []int{12}
}

func (x *StreamDiscovery) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type StreamDiscoveryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamDiscoveryResponse) Reset() {
	*x = StreamDiscoveryResponse{}
	mi := &file_veilnet_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamDiscoveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamDiscoveryResponse) ProtoMessage() {}

func (x *StreamDiscoveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_veilnet_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamDiscoveryResponse.ProtoReflect.Descriptor instead.
func (*StreamDiscoveryResponse) Descriptor() ([]byte, []int) {
	return file_veilnet_proto_rawDescGZIP(), []int{13}
}

type StreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_veilnet_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_veilnet_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_veilnet_proto_rawDescGZIP(), []int{14}
}

func (x *StreamRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *StreamRequest) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type StreamResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Cipher            []byte                 `protobuf:"bytes,2,opt,name=cipher,proto3" json:"cipher,omitempty"`
	EncryptedStreamId []byte                 `protobuf:"bytes,3,opt,name=encrypted_stream_id,json=encryptedStreamId,proto3" json:"encrypted_stream_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StreamResponse) Reset() {
	*x = StreamResponse{}
	mi := &file_veilnet_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResponse) ProtoMessage() {}

func (x *StreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_veilnet_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResponse.ProtoReflect.Descriptor instead.
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return file_veilnet_proto_rawDescGZIP(), []int{15}
}

func (x *StreamResponse) GetCipher() []byte {
	if x != nil {
		return x.Cipher
	}
	return nil
}

func (x *StreamResponse) GetEncryptedStreamId() []byte {
	if x != nil {
		return x.EncryptedStreamId
	}
	return nil
}

type StreamUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamUpdate) Reset() {
	*x = StreamUpdate{}
	mi := &file_veilnet_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamUpdate) ProtoMessage() {}

func (x *StreamUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_veilnet_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamUpdate.ProtoReflect.Descriptor instead.
func (*StreamUpdate) Descriptor() ([]byte, []int) {
	return file_veilnet_proto_rawDescGZIP(), []int{16}
}

func (x *StreamUpdate) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

type Echo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Echo) Reset() {
	*x = Echo{}
	mi := &file_veilnet_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Echo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Echo) ProtoMessage() {}

func (x *Echo) ProtoReflect() protoreflect.Message {
	mi := &file_veilnet_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Echo.ProtoReflect.Descriptor instead.
func (*Echo) Descriptor() ([]byte, []int) {
	return file_veilnet_proto_rawDescGZIP(), []int{17}
}

type Frame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_veilnet_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_veilnet_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_veilnet_proto_rawDescGZIP(), []int{18}
}

func (x *Frame) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Frames struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Frames        []*Frame               `protobuf:"bytes,1,rep,name=frames,proto3" json:"frames,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frames) Reset() {
	*x = Frames{}
	mi := &file_veilnet_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frames) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frames) ProtoMessage() {}

func (x *Frames) ProtoReflect() protoreflect.Message {
	mi := &file_veilnet_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frames.ProtoReflect.Descriptor instead.
func (*Frames) Descriptor() ([]byte, []int) {
	return file_veilnet_proto_rawDescGZIP(), []int{19}
}

func (x *Frames) GetFrames() []*Frame {
	if x != nil {
		return x.Frames
	}
	return nil
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dst           string                 `protobuf:"bytes,1,opt,name=dst,proto3" json:"dst,omitempty"`
	StreamId      string                 `protobuf:"bytes,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	RouteId       string                 `protobuf:"bytes,3,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_veilnet_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_veilnet_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_veilnet_proto_rawDescGZIP(), []int{20}
}

func (x *Data) GetDst() string {
	if x != nil {
		return x.Dst
	}
	return ""
}

func (x *Data) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *Data) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *Data) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type LocalNetwork struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subnet        string                 `protobuf:"bytes,1,opt,name=subnet,proto3" json:"subnet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalNetwork) Reset() {
	*x = LocalNetwork{}
	mi := &file_veilnet_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalNetwork) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalNetwork) ProtoMessage() {}

func (x *LocalNetwork) ProtoReflect() protoreflect.Message {
	mi := &file_veilnet_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalNetwork.ProtoReflect.Descriptor instead.
func (*LocalNetwork) Descriptor() ([]byte, []int) {
	return file_veilnet_proto_rawDescGZIP(), []int{21}
}

func (x *LocalNetwork) GetSubnet() string {
	if x != nil {
		return x.Subnet
	}
	return ""
}

type LocalNetworks struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocalNetworks []*LocalNetwork        `protobuf:"bytes,1,rep,name=local_networks,json=localNetworks,proto3" json:"local_networks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalNetworks) Reset() {
	*x = LocalNetworks{}
	mi := &file_veilnet_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalNetworks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalNetworks) ProtoMessage() {}

func (x *LocalNetworks) ProtoReflect() protoreflect.Message {
	mi := &file_veilnet_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalNetworks.ProtoReflect.Descriptor instead.
func (*LocalNetworks) Descriptor() ([]byte, []int) {
	return file_veilnet_proto_rawDescGZIP(), []int{22}
}

func (x *LocalNetworks) GetLocalNetworks() []*LocalNetwork {
	if x != nil {
		return x.LocalNetworks
	}
	return nil
}

type RemoteNetwork struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerSignature string                 `protobuf:"bytes,1,opt,name=peerSignature,proto3" json:"peerSignature,omitempty"`
	Subnet        string                 `protobuf:"bytes,2,opt,name=subnet,proto3" json:"subnet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteNetwork) Reset() {
	*x = RemoteNetwork{}
	mi := &file_veilnet_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteNetwork) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteNetwork) ProtoMessage() {}

func (x *RemoteNetwork) ProtoReflect() protoreflect.Message {
	mi := &file_veilnet_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteNetwork.ProtoReflect.Descriptor instead.
func (*RemoteNetwork) Descriptor() ([]byte, []int) {
	return file_veilnet_proto_rawDescGZIP(), []int{23}
}

func (x *RemoteNetwork) GetPeerSignature() string {
	if x != nil {
		return x.PeerSignature
	}
	return ""
}

func (x *RemoteNetwork) GetSubnet() string {
	if x != nil {
		return x.Subnet
	}
	return ""
}

type RemoteNetworks struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RemoteNetworks []*RemoteNetwork       `protobuf:"bytes,1,rep,name=remote_networks,json=remoteNetworks,proto3" json:"remote_networks,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RemoteNetworks) Reset() {
	*x = RemoteNetworks{}
	mi := &file_veilnet_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteNetworks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteNetworks) ProtoMessage() {}

func (x *RemoteNetworks) ProtoReflect() protoreflect.Message {
	mi := &file_veilnet_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteNetworks.ProtoReflect.Descriptor instead.
func (*RemoteNetworks) Descriptor() ([]byte, []int) {
	return file_veilnet_proto_rawDescGZIP(), []int{24}
}

func (x *RemoteNetworks) GetRemoteNetworks() []*RemoteNetwork {
	if x != nil {
		return x.RemoteNetworks
	}
	return nil
}

type Cmd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          CmdType                `protobuf:"varint,1,opt,name=type,proto3,enum=veilnet.CmdType" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cmd) Reset() {
	*x = Cmd{}
	mi := &file_veilnet_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cmd) ProtoMessage() {}

func (x *Cmd) ProtoReflect() protoreflect.Message {
	mi := &file_veilnet_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cmd.ProtoReflect.Descriptor instead.
func (*Cmd) Descriptor() ([]byte, []int) {
	return file_veilnet_proto_rawDescGZIP(), []int{25}
}

func (x *Cmd) GetType() CmdType {
	if x != nil {
		return x.Type
	}
	return CmdType_SHUTDOWN
}

func (x *Cmd) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type CmdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Response      string                 `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdResponse) Reset() {
	*x = CmdResponse{}
	mi := &file_veilnet_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdResponse) ProtoMessage() {}

func (x *CmdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_veilnet_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdResponse.ProtoReflect.Descriptor instead.
func (*CmdResponse) Descriptor() ([]byte, []int) {
	return file_veilnet_proto_rawDescGZIP(), []int{26}
}

func (x *CmdResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CmdResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type Shutdown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shutdown) Reset() {
	*x = Shutdown{}
	mi := &file_veilnet_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shutdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shutdown) ProtoMessage() {}

func (x *Shutdown) ProtoReflect() protoreflect.Message {
	mi := &file_veilnet_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shutdown.ProtoReflect.Descriptor instead.
func (*Shutdown) Descriptor() ([]byte, []int) {
	return file_veilnet_proto_rawDescGZIP(), []int{27}
}

func (x *Shutdown) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type QueryLocalNetwork struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryLocalNetwork) Reset() {
	*x = QueryLocalNetwork{}
	mi := &file_veilnet_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryLocalNetwork) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryLocalNetwork) ProtoMessage() {}

func (x *QueryLocalNetwork) ProtoReflect() protoreflect.Message {
	mi := &file_veilnet_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryLocalNetwork.ProtoReflect.Descriptor instead.
func (*QueryLocalNetwork) Descriptor() ([]byte, []int) {
	return file_veilnet_proto_rawDescGZIP(), []int{28}
}

type QueryRemoteNetwork struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRemoteNetwork) Reset() {
	*x = QueryRemoteNetwork{}
	mi := &file_veilnet_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRemoteNetwork) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRemoteNetwork) ProtoMessage() {}

func (x *QueryRemoteNetwork) ProtoReflect() protoreflect.Message {
	mi := &file_veilnet_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRemoteNetwork.ProtoReflect.Descriptor instead.
func (*QueryRemoteNetwork) Descriptor() ([]byte, []int) {
	return file_veilnet_proto_rawDescGZIP(), []int{29}
}

type Scope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     []byte                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scope) Reset() {
	*x = Scope{}
	mi := &file_veilnet_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scope) ProtoMessage() {}

func (x *Scope) ProtoReflect() protoreflect.Message {
	mi := &file_veilnet_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scope.ProtoReflect.Descriptor instead.
func (*Scope) Descriptor() ([]byte, []int) {
	return file_veilnet_proto_rawDescGZIP(), []int{30}
}

func (x *Scope) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type ScopeUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scopes        []*Scope               `protobuf:"bytes,1,rep,name=scopes,proto3" json:"scopes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScopeUpdate) Reset() {
	*x = ScopeUpdate{}
	mi := &file_veilnet_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScopeUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScopeUpdate) ProtoMessage() {}

func (x *ScopeUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_veilnet_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScopeUpdate.ProtoReflect.Descriptor instead.
func (*ScopeUpdate) Descriptor() ([]byte, []int) {
	return file_veilnet_proto_rawDescGZIP(), []int{31}
}

func (x *ScopeUpdate) GetScopes() []*Scope {
	if x != nil {
		return x.Scopes
	}
	return nil
}

type StartAnchorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuardianUrl   string                 `protobuf:"bytes,1,opt,name=guardian_url,json=guardianUrl,proto3" json:"guardian_url,omitempty"`
	VeilUrl       string                 `protobuf:"bytes,2,opt,name=veil_url,json=veilUrl,proto3" json:"veil_url,omitempty"`
	VeilPort      int32                  `protobuf:"varint,3,opt,name=veil_port,json=veilPort,proto3" json:"veil_port,omitempty"`
	AnchorToken   string                 `protobuf:"bytes,4,opt,name=anchor_token,json=anchorToken,proto3" json:"anchor_token,omitempty"`
	Portal        bool                   `protobuf:"varint,5,opt,name=portal,proto3" json:"portal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartAnchorRequest) Reset() {
	*x = StartAnchorRequest{}
	mi := &file_veilnet_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartAnchorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartAnchorRequest) ProtoMessage() {}

func (x *StartAnchorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_veilnet_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartAnchorRequest.ProtoReflect.Descriptor instead.
func (*StartAnchorRequest) Descriptor() ([]byte, []int) {
	return file_veilnet_proto_rawDescGZIP(), []int{32}
}

func (x *StartAnchorRequest) GetGuardianUrl() string {
	if x != nil {
		return x.GuardianUrl
	}
	return ""
}

func (x *StartAnchorRequest) GetVeilUrl() string {
	if x != nil {
		return x.VeilUrl
	}
	return ""
}

func (x *StartAnchorRequest) GetVeilPort() int32 {
	if x != nil {
		return x.VeilPort
	}
	return 0
}

func (x *StartAnchorRequest) GetAnchorToken() string {
	if x != nil {
		return x.AnchorToken
	}
	return ""
}

func (x *StartAnchorRequest) GetPortal() bool {
	if x != nil {
		return x.Portal
	}
	return false
}

type CreateTUNRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ifname        string                 `protobuf:"bytes,1,opt,name=ifname,proto3" json:"ifname,omitempty"`
	Mtu           int32                  `protobuf:"varint,2,opt,name=mtu,proto3" json:"mtu,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTUNRequest) Reset() {
	*x = CreateTUNRequest{}
	mi := &file_veilnet_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTUNRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTUNRequest) ProtoMessage() {}

func (x *CreateTUNRequest) ProtoReflect() protoreflect.Message {
	mi := &file_veilnet_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTUNRequest.ProtoReflect.Descriptor instead.
func (*CreateTUNRequest) Descriptor() ([]byte, []int) {
	return file_veilnet_proto_rawDescGZIP(), []int{33}
}

func (x *CreateTUNRequest) GetIfname() string {
	if x != nil {
		return x.Ifname
	}
	return ""
}

func (x *CreateTUNRequest) GetMtu() int32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

type AttachWithFileDescriptorRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FileDescriptor int32                  `protobuf:"varint,1,opt,name=file_descriptor,json=fileDescriptor,proto3" json:"file_descriptor,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AttachWithFileDescriptorRequest) Reset() {
	*x = AttachWithFileDescriptorRequest{}
	mi := &file_veilnet_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachWithFileDescriptorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachWithFileDescriptorRequest) ProtoMessage() {}

func (x *AttachWithFileDescriptorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_veilnet_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachWithFileDescriptorRequest.ProtoReflect.Descriptor instead.
func (*AttachWithFileDescriptorRequest) Descriptor() ([]byte, []int) {
	return file_veilnet_proto_rawDescGZIP(), []int{34}
}

func (x *AttachWithFileDescriptorRequest) GetFileDescriptor() int32 {
	if x != nil {
		return x.FileDescriptor
	}
	return 0
}

type GetIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIDResponse) Reset() {
	*x = GetIDResponse{}
	mi := &file_veilnet_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIDResponse) ProtoMessage() {}

func (x *GetIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_veilnet_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIDResponse.ProtoReflect.Descriptor instead.
func (*GetIDResponse) Descriptor() ([]byte, []int) {
	return file_veilnet_proto_rawDescGZIP(), []int{35}
}

func (x *GetIDResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetCIDRResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cidr          string                 `protobuf:"bytes,1,opt,name=cidr,proto3" json:"cidr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCIDRResponse) Reset() {
	*x = GetCIDRResponse{}
	mi := &file_veilnet_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCIDRResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCIDRResponse) ProtoMessage() {}

func (x *GetCIDRResponse) ProtoReflect() protoreflect.Message {
	mi := &file_veilnet_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCIDRResponse.ProtoReflect.Descriptor instead.
func (*GetCIDRResponse) Descriptor() ([]byte, []int) {
	return file_veilnet_proto_rawDescGZIP(), []int{36}
}

func (x *GetCIDRResponse) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

type AddTaintRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     []byte                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTaintRequest) Reset() {
	*x = AddTaintRequest{}
	mi := &file_veilnet_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTaintRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTaintRequest) ProtoMessage() {}

func (x *AddTaintRequest) ProtoReflect() protoreflect.Message {
	mi := &file_veilnet_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTaintRequest.ProtoReflect.Descriptor instead.
func (*AddTaintRequest) Descriptor() ([]byte, []int) {
	return file_veilnet_proto_rawDescGZIP(), []int{37}
}

func (x *AddTaintRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type RemoveTaintRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     []byte                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveTaintRequest) Reset() {
	*x = RemoveTaintRequest{}
	mi := &file_veilnet_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveTaintRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTaintRequest) ProtoMessage() {}

func (x *RemoveTaintRequest) ProtoReflect() protoreflect.Message {
	mi := &file_veilnet_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTaintRequest.ProtoReflect.Descriptor instead.
func (*RemoveTaintRequest) Descriptor() ([]byte, []int) {
	return file_veilnet_proto_rawDescGZIP(), []int{38}
}

func (x *RemoveTaintRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_veilnet_proto protoreflect.FileDescriptor

const file_veilnet_proto_rawDesc = "" +
	"\n" +
	"\rveilnet.proto\x12\aveilnet\x1a\x1bgoogle/protobuf/empty.proto\"\xac\x02\n" +
	"\x06Header\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.veilnet.MessageTypeR\x04type\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\tR\tsignature\x12!\n" +
	"\x04role\x18\x03 \x01(\x0e2\r.veilnet.RoleR\x04role\x12\x16\n" +
	"\x06length\x18\x04 \x01(\rR\x06length\x12(\n" +
	"\x10mldsa_public_key\x18\x05 \x01(\fR\x0emldsaPublicKey\x12'\n" +
	"\x0fmldsa_signature\x18\x06 \x01(\fR\x0emldsaSignature\x12\x16\n" +
	"\x06scopes\x18\a \x03(\fR\x06scopes\x12\x16\n" +
	"\x06taints\x18\b \x03(\fR\x06taints\x12\x1c\n" +
	"\ttimestamp\x18\t \x01(\x03R\ttimestamp\"\\\n" +
	"\tRTC_Offer\x12\x1b\n" +
	"\ttether_id\x18\x01 \x01(\tR\btetherId\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\tR\tsignature\x12\x14\n" +
	"\x05offer\x18\x03 \x01(\fR\x05offer\"_\n" +
	"\n" +
	"RTC_Answer\x12\x1b\n" +
	"\ttether_id\x18\x01 \x01(\tR\btetherId\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\tR\tsignature\x12\x16\n" +
	"\x06answer\x18\x03 \x01(\fR\x06answer\"K\n" +
	"\x0eCandidateOffer\x12\x1b\n" +
	"\ttether_id\x18\x01 \x01(\tR\btetherId\x12\x1c\n" +
	"\tcandidate\x18\x02 \x01(\tR\tcandidate\"\x11\n" +
	"\x0fCandidateAccept\"h\n" +
	"\x03ICE\x12\x1b\n" +
	"\ttether_id\x18\x01 \x01(\tR\btetherId\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\tR\tsignature\x12\x14\n" +
	"\x05ufrag\x18\x03 \x01(\tR\x05ufrag\x12\x10\n" +
	"\x03pwd\x18\x04 \x01(\tR\x03pwd\"*\n" +
	"\n" +
	"ArpRequest\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\tR\tsignature\"\x8d\x01\n" +
	"\vArpResponse\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\tR\tsignature\x12\x10\n" +
	"\x03dst\x18\x02 \x01(\tR\x03dst\x12\x16\n" +
	"\x06weight\x18\x03 \x01(\x03R\x06weight\x12\x12\n" +
	"\x04hops\x18\x04 \x01(\x03R\x04hops\x12\x12\n" +
	"\x04path\x18\x05 \x03(\tR\x04path\x12\x0e\n" +
	"\x02id\x18\x06 \x01(\tR\x02id\"/\n" +
	"\tArpUpdate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04hops\x18\x02 \x01(\x03R\x04hops\"\x1a\n" +
	"\bDNSOffer\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\"\"\n" +
	"\bDNSQuery\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\"\x1d\n" +
	"\vDNSResponse\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\"!\n" +
	"\x0fStreamDiscovery\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\"\x19\n" +
	"\x17StreamDiscoveryResponse\">\n" +
	"\rStreamRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\fR\tpublicKey\"X\n" +
	"\x0eStreamResponse\x12\x16\n" +
	"\x06cipher\x18\x02 \x01(\fR\x06cipher\x12.\n" +
	"\x13encrypted_stream_id\x18\x03 \x01(\fR\x11encryptedStreamId\"+\n" +
	"\fStreamUpdate\x12\x1b\n" +
	"\tstream_id\x18\x02 \x01(\tR\bstreamId\"\x06\n" +
	"\x04Echo\"\x1b\n" +
	"\x05Frame\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"0\n" +
	"\x06Frames\x12&\n" +
	"\x06frames\x18\x01 \x03(\v2\x0e.veilnet.FrameR\x06frames\"j\n" +
	"\x04Data\x12\x10\n" +
	"\x03dst\x18\x01 \x01(\tR\x03dst\x12\x1b\n" +
	"\tstream_id\x18\x02 \x01(\tR\bstreamId\x12\x19\n" +
	"\broute_id\x18\x03 \x01(\tR\arouteId\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"&\n" +
	"\fLocalNetwork\x12\x16\n" +
	"\x06subnet\x18\x01 \x01(\tR\x06subnet\"M\n" +
	"\rLocalNetworks\x12<\n" +
	"\x0elocal_networks\x18\x01 \x03(\v2\x15.veilnet.LocalNetworkR\rlocalNetworks\"M\n" +
	"\rRemoteNetwork\x12$\n" +
	"\rpeerSignature\x18\x01 \x01(\tR\rpeerSignature\x12\x16\n" +
	"\x06subnet\x18\x02 \x01(\tR\x06subnet\"Q\n" +
	"\x0eRemoteNetworks\x12?\n" +
	"\x0fremote_networks\x18\x01 \x03(\v2\x16.veilnet.RemoteNetworkR\x0eremoteNetworks\"E\n" +
	"\x03Cmd\x12$\n" +
	"\x04type\x18\x01 \x01(\x0e2\x10.veilnet.CmdTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"C\n" +
	"\vCmdResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1a\n" +
	"\bresponse\x18\x02 \x01(\tR\bresponse\"\"\n" +
	"\bShutdown\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\x13\n" +
	"\x11QueryLocalNetwork\"\x14\n" +
	"\x12QueryRemoteNetwork\"%\n" +
	"\x05Scope\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\fR\tsignature\"5\n" +
	"\vScopeUpdate\x12&\n" +
	"\x06scopes\x18\x01 \x03(\v2\x0e.veilnet.ScopeR\x06scopes\"\xaa\x01\n" +
	"\x12StartAnchorRequest\x12!\n" +
	"\fguardian_url\x18\x01 \x01(\tR\vguardianUrl\x12\x19\n" +
	"\bveil_url\x18\x02 \x01(\tR\aveilUrl\x12\x1b\n" +
	"\tveil_port\x18\x03 \x01(\x05R\bveilPort\x12!\n" +
	"\fanchor_token\x18\x04 \x01(\tR\vanchorToken\x12\x16\n" +
	"\x06portal\x18\x05 \x01(\bR\x06portal\"<\n" +
	"\x10CreateTUNRequest\x12\x16\n" +
	"\x06ifname\x18\x01 \x01(\tR\x06ifname\x12\x10\n" +
	"\x03mtu\x18\x02 \x01(\x05R\x03mtu\"J\n" +
	"\x1fAttachWithFileDescriptorRequest\x12'\n" +
	"\x0ffile_descriptor\x18\x01 \x01(\x05R\x0efileDescriptor\"\x1f\n" +
	"\rGetIDResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"%\n" +
	"\x0fGetCIDRResponse\x12\x12\n" +
	"\x04cidr\x18\x01 \x01(\tR\x04cidr\"/\n" +
	"\x0fAddTaintRequest\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\fR\tsignature\"2\n" +
	"\x12RemoveTaintRequest\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\fR\tsignature*\x98\x03\n" +
	"\vMessageType\x12\r\n" +
	"\tRTC_OFFER\x10\x00\x12\x0e\n" +
	"\n" +
	"RTC_ANSWER\x10\x01\x12\x13\n" +
	"\x0fCANDIDATE_OFFER\x10\x02\x12\x11\n" +
	"\rICE_CANDIDATE\x10\x03\x12\r\n" +
	"\tICE_OFFER\x10\x04\x12\x0e\n" +
	"\n" +
	"ICE_ANSWER\x10\x05\x12\r\n" +
	"\tDNS_QUERY\x10\x06\x12\x0e\n" +
	"\n" +
	"DNS_ANSWER\x10\a\x12\x0f\n" +
	"\vARP_REQUEST\x10\b\x12\x10\n" +
	"\fARP_RESPONSE\x10\t\x12\x0e\n" +
	"\n" +
	"ARP_UPDATE\x10\n" +
	"\x12\x14\n" +
	"\x10STREAM_DISCOVERY\x10\v\x12\x1d\n" +
	"\x19STREAM_DISCOVERY_RESPONSE\x10\f\x12\x12\n" +
	"\x0eSTREAM_REQUEST\x10\r\x12\x13\n" +
	"\x0fSTREAM_RESPONSE\x10\x0e\x12\x11\n" +
	"\rSTREAM_UPDATE\x10\x0f\x12\b\n" +
	"\x04ECHO\x10\x10\x12\b\n" +
	"\x04DATA\x10\x11\x12\x16\n" +
	"\x12ADD_REMOTE_NETWORK\x10\x12\x12\x19\n" +
	"\x15REMOVE_REMOTE_NETWORK\x10\x13\x12\a\n" +
	"\x03CMD\x10\x14\x12\x10\n" +
	"\fCMD_RESPONSE\x10\x15*\\\n" +
	"\aCmdType\x12\f\n" +
	"\bSHUTDOWN\x10\x00\x12\x17\n" +
	"\x13QUERY_LOCAL_NETWORK\x10\x01\x12\x18\n" +
	"\x14QUERY_REMOTE_NETWORK\x10\x02\x12\x10\n" +
	"\fSCOPE_UPDATE\x10\x03*!\n" +
	"\x04Role\x12\f\n" +
	"\bGUARDIAN\x10\x00\x12\v\n" +
	"\aCONFLUX\x10\x012\x9f\x05\n" +
	"\x06Anchor\x12B\n" +
	"\vStartAnchor\x12\x1b.veilnet.StartAnchorRequest\x1a\x16.google.protobuf.Empty\x12<\n" +
	"\n" +
	"StopAnchor\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12>\n" +
	"\tCreateTUN\x12\x19.veilnet.CreateTUNRequest\x1a\x16.google.protobuf.Empty\x12<\n" +
	"\n" +
	"DestroyTUN\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12?\n" +
	"\rAttachWithTUN\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12\\\n" +
	"\x18AttachWithFileDescriptor\x12(.veilnet.AttachWithFileDescriptorRequest\x1a\x16.google.protobuf.Empty\x127\n" +
	"\x05GetID\x12\x16.google.protobuf.Empty\x1a\x16.veilnet.GetIDResponse\x12;\n" +
	"\aGetCIDR\x12\x16.google.protobuf.Empty\x1a\x18.veilnet.GetCIDRResponse\x12<\n" +
	"\bAddTaint\x12\x18.veilnet.AddTaintRequest\x1a\x16.google.protobuf.Empty\x12B\n" +
	"\vRemoveTaint\x12\x1b.veilnet.RemoveTaintRequest\x1a\x16.google.protobuf.EmptyB#Z!github.com/veil-net/conflux/protob\x06proto3"

var (
	file_veilnet_proto_rawDescOnce sync.Once
	file_veilnet_proto_rawDescData []byte
)

func file_veilnet_proto_rawDescGZIP() []byte {
	file_veilnet_proto_rawDescOnce.Do(func() {
		file_veilnet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_veilnet_proto_rawDesc), len(file_veilnet_proto_rawDesc)))
	})
	return file_veilnet_proto_rawDescData
}

var file_veilnet_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_veilnet_proto_msgTypes = make([]protoimpl.MessageInfo, 39)
var file_veilnet_proto_goTypes = []any{
	(MessageType)(0),                        // 0: veilnet.MessageType
	(CmdType)(0),                            // 1: veilnet.CmdType
	(Role)(0),                               // 2: veilnet.Role
	(*Header)(nil),                          // 3: veilnet.Header
	(*RTC_Offer)(nil),                       // 4: veilnet.RTC_Offer
	(*RTC_Answer)(nil),                      // 5: veilnet.RTC_Answer
	(*CandidateOffer)(nil),                  // 6: veilnet.CandidateOffer
	(*CandidateAccept)(nil),                 // 7: veilnet.CandidateAccept
	(*ICE)(nil),                             // 8: veilnet.ICE
	(*ArpRequest)(nil),                      // 9: veilnet.ArpRequest
	(*ArpResponse)(nil),                     // 10: veilnet.ArpResponse
	(*ArpUpdate)(nil),                       // 11: veilnet.ArpUpdate
	(*DNSOffer)(nil),                        // 12: veilnet.DNSOffer
	(*DNSQuery)(nil),                        // 13: veilnet.DNSQuery
	(*DNSResponse)(nil),                     // 14: veilnet.DNSResponse
	(*StreamDiscovery)(nil),                 // 15: veilnet.StreamDiscovery
	(*StreamDiscoveryResponse)(nil),         // 16: veilnet.StreamDiscoveryResponse
	(*StreamRequest)(nil),                   // 17: veilnet.StreamRequest
	(*StreamResponse)(nil),                  // 18: veilnet.StreamResponse
	(*StreamUpdate)(nil),                    // 19: veilnet.StreamUpdate
	(*Echo)(nil),                            // 20: veilnet.Echo
	(*Frame)(nil),                           // 21: veilnet.Frame
	(*Frames)(nil),                          // 22: veilnet.Frames
	(*Data)(nil),                            // 23: veilnet.Data
	(*LocalNetwork)(nil),                    // 24: veilnet.LocalNetwork
	(*LocalNetworks)(nil),                   // 25: veilnet.LocalNetworks
	(*RemoteNetwork)(nil),                   // 26: veilnet.RemoteNetwork
	(*RemoteNetworks)(nil),                  // 27: veilnet.RemoteNetworks
	(*Cmd)(nil),                             // 28: veilnet.Cmd
	(*CmdResponse)(nil),                     // 29: veilnet.CmdResponse
	(*Shutdown)(nil),                        // 30: veilnet.Shutdown
	(*QueryLocalNetwork)(nil),               // 31: veilnet.QueryLocalNetwork
	(*QueryRemoteNetwork)(nil),              // 32: veilnet.QueryRemoteNetwork
	(*Scope)(nil),                           // 33: veilnet.Scope
	(*ScopeUpdate)(nil),                     // 34: veilnet.ScopeUpdate
	(*StartAnchorRequest)(nil),              // 35: veilnet.StartAnchorRequest
	(*CreateTUNRequest)(nil),                // 36: veilnet.CreateTUNRequest
	(*AttachWithFileDescriptorRequest)(nil), // 37: veilnet.AttachWithFileDescriptorRequest
	(*GetIDResponse)(nil),                   // 38: veilnet.GetIDResponse
	(*GetCIDRResponse)(nil),                 // 39: veilnet.GetCIDRResponse
	(*AddTaintRequest)(nil),                 // 40: veilnet.AddTaintRequest
	(*RemoveTaintRequest)(nil),              // 41: veilnet.RemoveTaintRequest
	(*emptypb.Empty)(nil),                   // 42: google.protobuf.Empty
}
var file_veilnet_proto_depIdxs = []int32{
	0,  // 0: veilnet.Header.type:type_name -> veilnet.MessageType
	2,  // 1: veilnet.Header.role:type_name -> veilnet.Role
	21, // 2: veilnet.Frames.frames:type_name -> veilnet.Frame
	24, // 3: veilnet.LocalNetworks.local_networks:type_name -> veilnet.LocalNetwork
	26, // 4: veilnet.RemoteNetworks.remote_networks:type_name -> veilnet.RemoteNetwork
	1,  // 5: veilnet.Cmd.type:type_name -> veilnet.CmdType
	33, // 6: veilnet.ScopeUpdate.scopes:type_name -> veilnet.Scope
	35, // 7: veilnet.Anchor.StartAnchor:input_type -> veilnet.StartAnchorRequest
	42, // 8: veilnet.Anchor.StopAnchor:input_type -> google.protobuf.Empty
	36, // 9: veilnet.Anchor.CreateTUN:input_type -> veilnet.CreateTUNRequest
	42, // 10: veilnet.Anchor.DestroyTUN:input_type -> google.protobuf.Empty
	42, // 11: veilnet.Anchor.AttachWithTUN:input_type -> google.protobuf.Empty
	37, // 12: veilnet.Anchor.AttachWithFileDescriptor:input_type -> veilnet.AttachWithFileDescriptorRequest
	42, // 13: veilnet.Anchor.GetID:input_type -> google.protobuf.Empty
	42, // 14: veilnet.Anchor.GetCIDR:input_type -> google.protobuf.Empty
	40, // 15: veilnet.Anchor.AddTaint:input_type -> veilnet.AddTaintRequest
	41, // 16: veilnet.Anchor.RemoveTaint:input_type -> veilnet.RemoveTaintRequest
	42, // 17: veilnet.Anchor.StartAnchor:output_type -> google.protobuf.Empty
	42, // 18: veilnet.Anchor.StopAnchor:output_type -> google.protobuf.Empty
	42, // 19: veilnet.Anchor.CreateTUN:output_type -> google.protobuf.Empty
	42, // 20: veilnet.Anchor.DestroyTUN:output_type -> google.protobuf.Empty
	42, // 21: veilnet.Anchor.AttachWithTUN:output_type -> google.protobuf.Empty
	42, // 22: veilnet.Anchor.AttachWithFileDescriptor:output_type -> google.protobuf.Empty
	38, // 23: veilnet.Anchor.GetID:output_type -> veilnet.GetIDResponse
	39, // 24: veilnet.Anchor.GetCIDR:output_type -> veilnet.GetCIDRResponse
	42, // 25: veilnet.Anchor.AddTaint:output_type -> google.protobuf.Empty
	42, // 26: veilnet.Anchor.RemoveTaint:output_type -> google.protobuf.Empty
	17, // [17:27] is the sub-list for method output_type
	7,  // [7:17] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_veilnet_proto_init() }
func file_veilnet_proto_init() {
	if File_veilnet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_veilnet_proto_rawDesc), len(file_veilnet_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   39,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_veilnet_proto_goTypes,
		DependencyIndexes: file_veilnet_proto_depIdxs,
		EnumInfos:         file_veilnet_proto_enumTypes,
		MessageInfos:      file_veilnet_proto_msgTypes,
	}.Build()
	File_veilnet_proto = out.File
	file_veilnet_proto_goTypes = nil
	file_veilnet_proto_depIdxs = nil
}
